apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx-demo
    app.kubernetes.io/instance: nginx-demo-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: nginx-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - image: 756241702314.dkr.ecr.us-east-2.amazonaws.com/nginx-demo:latest
        imagePullPolicy: Always
        name: nginx-demo
        ports:
          - containerPort: 80