apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nginx-demo
    app.kubernetes.io/instance: nginx-demo-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: nginx-demo

spec:
  selector:
    app: nginx-demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    