apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig


metadata:
  name: eks-cicd-test #Cluster name
  region: us-east-2


nodeGroups:
  - name: ng-1 #cluster node name
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      allow: false